spring:
  application:
    name: feignclient
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 0

print:
  me: Devprofile

eureka:
  instance:
    preferIpAddress: true
    
hazelcast:
  network:
    join:
      multicast:
        enabled: true
