spring:
  application:
    name: feignclient
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8082

print:
  me: Devprofile

eureka:
  instance:
    preferIpAddress: true
