spring:
  application:
    name: microserviceone
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true
  elasticsearch:
    password: bIBas8zvAitjDdSeSWwf
    username: elastic
    

server:
  port: 8081

print:
  me: Dev profile
