spring:
  application:
    name: microserviceone
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8081

print:
  me: Dev profile

spring:
  elasticsearch:
    uris: https://localhost:9200
