spring:
  application:
    name: microserviceone
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8081

print:
  me: Devprofile

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761
  instance:
    preferIpAddress: true
